baseurl: https://www.dataviz.jp/
languageCode: ja
title: データの道具箱
copyright: "dataviz.jp"
DefaultContentLanguage: ja
hasCJKLanguage: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true


pagination:
  pagerSize: 20

taxonomies:
  category: categories
  tag: tags

services:
  disqus:
    shortname: ""
  googleAnalytics:
    id: "G-7NYMBRBRWZ"

permalinks:
  post: /:slug/
  page: /:slug/

params:
  defaultImage:
    opengraph:
      enabled: true
      local: false
      src: img/avatar.png
  opengraph:
    twitter:
      site: visualizing_jp
      card: summary
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: /favicon.ico
  widthClass: extended

  footer:
    since: 2024
    customText: ""

  dateFormat:
    published: "2006-01-02"
    lastUpdated: "2006-01-02"

  sidebar:
    emoji: 📊
    subtitle: データ可視化とデータ加工の便利ツール集
    avatar:
      enabled: false
      local: true
      src: img/avatar.png
    author:
      name: 矢崎裕一／Yuichi Yazaki
      image: img/avatar.png
      bio: 株式会社ビジネス・アーキテクツにてユーザー・インターフェイス・デザイナーおよびアート・ディレクターを7年間経験後、独立。企業や教育機関での講義活動、ウェブサイトVisualizing.JPにおける情報発信、コミュニティData Visualization Japanにおけるコミュニティ活動など、データ可視化の実践と普及に関するさまざまな活動をおこなっている。共著書に『RESASの教科書』(日経BP、2016)がある。千葉工業大学デザイン科学修士修了。データ・ビジュアライゼーション・ジャパン発起人/Yahoo!ニュース・エキスパート。
    categories:
      order:
        - data-visualization
        - data-visualization-map
        - data-visualization-parts
        - data-visualization-color
        - data-wrangling
        - data-wrangling-map

  widgets:
    frontpage:
      - type: page-links
        params:
          links:
            - name: 機能紹介
              url: "/overview/"
            - name: 料金プラン
              url: "/pricing/"
            - name: よくある質問
              url: "/faq/"
            - name: 利用規約
              url: "/terms/"
            - name: プライバシー・ポリシー
              url: "/privacy/"
            - name: お問い合わせ
              url: "/contact/"
            - name: 運営会社
              url: "/about/"

  article:
    math: false
    toc: true
    readingTime: false
    license:
      enabled: false
      default: ""

  comments:
    enabled: false
    provider: disqus

  colorScheme:
    toggle: false
    default: light

markup:
  goldmark:
    renderer:
      unsafe: true
theme: hugo-theme-stack
